---
- name: enter container and modify ssh
  hosts: all
  gather_facts: false
  tasks:
    - name: modify ssh
      ansible.builtin.shell:
        cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak &&
        echo "PermitRootLogin yes" >> /etc/ssh/sshd_config &&
        echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config &&
        systemctl restart ssh
